import LaunchIcon from "@mui/icons-material/Launch";
import GitHubIcon from "@mui/icons-material/GitHub";

export const react = [
  {
    id: 0,
    linkPath: "https://coindasher.netlify.app/",
    gitHubPath: "https://github.com/jayeshtele/crypto-app",
    imagePath: "/assets/coindasher.png",
    linkIcon: <LaunchIcon />,
    gitHubIcon: <GitHubIcon />,
  },
  {
    id: 1,
    linkPath: "https://spotify-2-0-melody-music-clone.netlify.app/",
    gitHubPath: "https://github.com/jayeshtele/spotify-2.0-clone",
    imagePath: "/assets/melody.png",
    linkIcon: <LaunchIcon />,
    gitHubIcon: <GitHubIcon />,
  },
  {
    id: 2,
    linkPath: "https://jayesh-tic-tac-game.netlify.app/",
    gitHubPath: "https://github.com/jayeshtele/Tic-Tac-Toe-App",
    imagePath: "/assets/TicTacToe.png",
    linkIcon: <LaunchIcon />,
    gitHubIcon: <GitHubIcon />,
  },
];

export const javascript = [
  {
    id: 0,
    linkPath: "https://cash-return-app.netlify.app/",
    gitHubPath: "https://github.com/jayeshtele/Cash-Register-Manager-App",
    imagePath: "/assets/CashManager.png",
    linkIcon: <LaunchIcon />,
    gitHubIcon: <GitHubIcon />,
  },
  {
    id: 1,
    linkPath: "https://jayeshtele-fun-translate-app.netlify.app/",
    gitHubPath: "https://github.com/jayeshtele/Fun-Translation-App",
    imagePath: "/assets/TranslaterApp.png",
    linkIcon: <LaunchIcon />,
    gitHubIcon: <GitHubIcon />,
  },
  {
    id: 2,
    linkPath: "https://stocks-profit-loss-giver-app.netlify.app/",
    gitHubPath: "https://github.com/jayeshtele/Stocks-Profit-Loss-App",
    imagePath: "/assets/Stocks.png",
    linkIcon: <LaunchIcon />,
    gitHubIcon: <GitHubIcon />,
  },
  {
    id: 3,
    linkPath: "https://jayeshtele-todo-list.netlify.app/",
    gitHubPath: "https://github.com/jayeshtele/To-Do-App",
    imagePath: "/assets/ToDoApp.png",
    linkIcon: <LaunchIcon />,
    gitHubIcon: <GitHubIcon />,
  },
  {
    id: 4,
    linkPath: "https://jayeshtele-calculator.netlify.app/",
    gitHubPath: "https://github.com/jayeshtele/Calculator",
    imagePath: "/assets/Calculator.png",
    linkIcon: <LaunchIcon />,
    gitHubIcon: <GitHubIcon />,
  },
];

export const htmlCss = [
  {
    id: 0,
    linkPath: "https://jayeshtele-wedding.netlify.app/",
    gitHubPath: "https://github.com/jayeshtele/Wedding",
    imagePath: "/assets/Wedding.png",
    linkIcon: <LaunchIcon />,
    gitHubIcon: <GitHubIcon />,
  },
  {
    id: 1,
    linkPath: "https://jayeshtele-garage.netlify.app/",
    gitHubPath: "https://github.com/jayeshtele/Garage",
    imagePath: "/assets/Garage.png",
    linkIcon: <LaunchIcon />,
    gitHubIcon: <GitHubIcon />,
  },
  {
    id: 2,
    linkPath: "https://jayeshtele-gym.netlify.app/",
    gitHubPath: "https://github.com/jayeshtele/Gym",
    imagePath: "/assets/Gym.png",
    linkIcon: <LaunchIcon />,
    gitHubIcon: <GitHubIcon />,
  },
  {
    id: 3,
    linkPath: "https://jayeshtele-bakery.netlify.app/",
    gitHubPath: "https://github.com/jayeshtele/Bakery",
    imagePath: "/assets/Bakery.png",
    linkIcon: <LaunchIcon />,
    gitHubIcon: <GitHubIcon />,
  },
  {
    id: 4,
    linkPath: "https://jayeshtele-education.netlify.app/",
    gitHubPath: "https://github.com/jayeshtele/Education",
    imagePath: "/assets/Education.png",
    linkIcon: <LaunchIcon />,
    gitHubIcon: <GitHubIcon />,
  },
  {
    id: 5,
    linkPath: "https://jayeshtele-bank.netlify.app/",
    gitHubPath: "https://github.com/jayeshtele/Bank",
    imagePath: "/assets/Bank.png",
    linkIcon: <LaunchIcon />,
    gitHubIcon: <GitHubIcon />,
  },
  {
    id: 6,
    linkPath: "https://jayeshtele-coffee-shop.netlify.app/",
    gitHubPath: "https://github.com/jayeshtele/Coffee-Shop",
    imagePath: "/assets/Cafe.png",
    linkIcon: <LaunchIcon />,
    gitHubIcon: <GitHubIcon />,
  },
  {
    id: 7,
    linkPath: "https://jayeshtele-fashion.netlify.app/",
    gitHubPath: "https://github.com/jayeshtele/Fashion",
    imagePath: "/assets/Fashion.png",
    linkIcon: <LaunchIcon />,
    gitHubIcon: <GitHubIcon />,
  },
  {
    id: 8,
    linkPath: "https://jayeshtele-salon.netlify.app/",
    gitHubPath: "https://github.com/jayeshtele/Salon",
    imagePath: "/assets/Salon.png",
    linkIcon: <LaunchIcon />,
    gitHubIcon: <GitHubIcon />,
  },
  {
    id: 9,
    linkPath: "https://jayeshtele-doctor.netlify.app/",
    gitHubPath: "https://github.com/jayeshtele/Doctor",
    imagePath: "/assets/Doctor.png",
    linkIcon: <LaunchIcon />,
    gitHubIcon: <GitHubIcon />,
  },
];
